---
sources:
  - /var/log/*.log: pipes.custom
  - /var/log/*/*.log:
      handler: pipes.custom
  - /var/log/syslog: {handler: pipes.custom}

pipes:
  custom:
    cls: logdog.roles.pipes.Pipe
    cls*:
      - watch processors.stripper
      - watch parsers.regex:
          regex: (?P<msg>.*)
      - view formatters.formatter
      - view viewers.console


  custom2:
    cls: tmp.paths
